/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersUserIdImport } from './routes/users/$userId'
import { Route as PostsPostIdImport } from './routes/posts/$postId'
import { Route as CreateUserImport } from './routes/create/user'
import { Route as CreatePostImport } from './routes/create/post'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdRoute = UsersUserIdImport.update({
  path: '/users/$userId',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

const CreateUserRoute = CreateUserImport.update({
  path: '/create/user',
  getParentRoute: () => rootRoute,
} as any)

const CreatePostRoute = CreatePostImport.update({
  path: '/create/post',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create/post': {
      id: '/create/post'
      path: '/create/post'
      fullPath: '/create/post'
      preLoaderRoute: typeof CreatePostImport
      parentRoute: typeof rootRoute
    }
    '/create/user': {
      id: '/create/user'
      path: '/create/user'
      fullPath: '/create/user'
      preLoaderRoute: typeof CreateUserImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CreatePostRoute,
  CreateUserRoute,
  PostsPostIdRoute,
  UsersUserIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create/post",
        "/create/user",
        "/posts/$postId",
        "/users/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create/post": {
      "filePath": "create/post.tsx"
    },
    "/create/user": {
      "filePath": "create/user.tsx"
    },
    "/posts/$postId": {
      "filePath": "posts/$postId.tsx"
    },
    "/users/$userId": {
      "filePath": "users/$userId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
