/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const AboutAuthorLazyImport = createFileRoute('/aboutAuthor')()

// Create/Update Routes

const AboutAuthorLazyRoute = AboutAuthorLazyImport.update({
  path: '/aboutAuthor',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/aboutAuthor.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/aboutAuthor': {
      id: '/aboutAuthor'
      path: '/aboutAuthor'
      fullPath: '/aboutAuthor'
      preLoaderRoute: typeof AboutAuthorLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutAuthorLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/aboutAuthor"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/aboutAuthor": {
      "filePath": "aboutAuthor.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
